# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FDU-gradhotpot
brief-intro: Anything related in graduate program admission!
baseurl: "/fdu-gradhotpot" # the subpath of your site, e.g. /blog
url: "https://fdu-cooks.github.io/" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: 
facebook_username: 
github_username:  
weibo_username: 
zhihu_username: 
linkedIn_username: 
dribbble_username:
email: 15300180012@fudan.edu.cn

description_footer: 本站记录每一届复旦申请CS/DS方向MS/PhD的资料！

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #hygblog
disqus_shortname: shun-blog

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 66b97f63670e7488b8493321c91f6c93  # shun
google_analytics_id:  # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
